package NewLanguage.structure;

/*Generated by MPS */

import jetbrains.mps.smodel.runtime.ConceptPresentationAspectBase;
import jetbrains.mps.smodel.runtime.ConceptPresentation;
import org.jetbrains.annotations.Nullable;
import org.jetbrains.mps.openapi.language.SAbstractConcept;
import jetbrains.mps.smodel.runtime.ConceptPresentationBuilder;

public class ConceptPresentationAspectImpl extends ConceptPresentationAspectBase {
  private ConceptPresentation props_API;
  private ConceptPresentation props_Action;
  private ConceptPresentation props_Aggregate;
  private ConceptPresentation props_AnalysingData;
  private ConceptPresentation props_Archive;
  private ConceptPresentation props_AsynchronousRequestReply;
  private ConceptPresentation props_Batch;
  private ConceptPresentation props_Classify;
  private ConceptPresentation props_Cleaning;
  private ConceptPresentation props_ClientServerConnection;
  private ConceptPresentation props_Cloud;
  private ConceptPresentation props_Column;
  private ConceptPresentation props_Component;
  private ConceptPresentation props_ComponentBehavior;
  private ConceptPresentation props_Compress;
  private ConceptPresentation props_ComputingUnit;
  private ConceptPresentation props_Connection;
  private ConceptPresentation props_ConnectionType;
  private ConceptPresentation props_ConsumingData;
  private ConceptPresentation props_DataArchitecture;
  private ConceptPresentation props_DataGeneration;
  private ConceptPresentation props_DataIngestion;
  private ConceptPresentation props_DataLinkableElement;
  private ConceptPresentation props_DataLocation;
  private ConceptPresentation props_DataPort;
  private ConceptPresentation props_DataProcessing;
  private ConceptPresentation props_Describe;
  private ConceptPresentation props_Diagnoze;
  private ConceptPresentation props_Document;
  private ConceptPresentation props_Edge;
  private ConceptPresentation props_EmbeddedFlashMemory;
  private ConceptPresentation props_Event;
  private ConceptPresentation props_FTP;
  private ConceptPresentation props_FileSystems;
  private ConceptPresentation props_Filter;
  private ConceptPresentation props_Fog;
  private ConceptPresentation props_Govern;
  private ConceptPresentation props_Graph;
  private ConceptPresentation props_HTTP_HTTPS;
  private ConceptPresentation props_Historical;
  private ConceptPresentation props_IPFS;
  private ConceptPresentation props_Identify;
  private ConceptPresentation props_InDataPort;
  private ConceptPresentation props_Integrate;
  private ConceptPresentation props_KeyValue;
  private ConceptPresentation props_Link;
  private ConceptPresentation props_LoadBalancer;
  private ConceptPresentation props_LocalStorage;
  private ConceptPresentation props_MQTT;
  private ConceptPresentation props_Math_Operation;
  private ConceptPresentation props_Merge;
  private ConceptPresentation props_MessageQueueing;
  private ConceptPresentation props_NVMe;
  private ConceptPresentation props_NetworkProtocols;
  private ConceptPresentation props_NewSQL;
  private ConceptPresentation props_NoSQL;
  private ConceptPresentation props_OutDataPort;
  private ConceptPresentation props_PointToPoint;
  private ConceptPresentation props_Predict;
  private ConceptPresentation props_Prescript;
  private ConceptPresentation props_ProcessingType;
  private ConceptPresentation props_PublisherSubscriberConnection;
  private ConceptPresentation props_PushPull;
  private ConceptPresentation props_Qualitative;
  private ConceptPresentation props_Quantitative;
  private ConceptPresentation props_QueryReport;
  private ConceptPresentation props_RealTime;
  private ConceptPresentation props_Real_Time;
  private ConceptPresentation props_ReceiveData;
  private ConceptPresentation props_ReduceNoise;
  private ConceptPresentation props_RequestResponse;
  private ConceptPresentation props_Retrieve;
  private ConceptPresentation props_SSDs;
  private ConceptPresentation props_Save;
  private ConceptPresentation props_SendData;
  private ConceptPresentation props_Sort;
  private ConceptPresentation props_Statistical;
  private ConceptPresentation props_StorageType;
  private ConceptPresentation props_StoringData;
  private ConceptPresentation props_Stream;
  private ConceptPresentation props_StreamProcessing;
  private ConceptPresentation props_TCP_IP;
  private ConceptPresentation props_Technique;
  private ConceptPresentation props_TimeStamp;
  private ConceptPresentation props_Transform;
  private ConceptPresentation props_Transforme;
  private ConceptPresentation props_Type;
  private ConceptPresentation props_Validate;
  private ConceptPresentation props_Visualize;
  private ConceptPresentation props_WebSocket;

  @Override
  @Nullable
  public ConceptPresentation getDescriptor(SAbstractConcept c) {
    StructureAspectDescriptor structureDescriptor = (StructureAspectDescriptor) myLanguageRuntime.getAspect(jetbrains.mps.smodel.runtime.StructureAspectDescriptor.class);
    switch (structureDescriptor.internalIndex(c)) {
      case LanguageConceptSwitch.API:
        if (props_API == null) {
          ConceptPresentationBuilder cpb = new ConceptPresentationBuilder();
          cpb.presentationByName();
          props_API = cpb.create();
        }
        return props_API;
      case LanguageConceptSwitch.Action:
        if (props_Action == null) {
          ConceptPresentationBuilder cpb = new ConceptPresentationBuilder();
          props_Action = cpb.create();
        }
        return props_Action;
      case LanguageConceptSwitch.Aggregate:
        if (props_Aggregate == null) {
          ConceptPresentationBuilder cpb = new ConceptPresentationBuilder();
          cpb.presentationByName();
          props_Aggregate = cpb.create();
        }
        return props_Aggregate;
      case LanguageConceptSwitch.AnalysingData:
        if (props_AnalysingData == null) {
          ConceptPresentationBuilder cpb = new ConceptPresentationBuilder();
          cpb.presentationByName();
          props_AnalysingData = cpb.create();
        }
        return props_AnalysingData;
      case LanguageConceptSwitch.Archive:
        if (props_Archive == null) {
          ConceptPresentationBuilder cpb = new ConceptPresentationBuilder();
          cpb.presentationByName();
          props_Archive = cpb.create();
        }
        return props_Archive;
      case LanguageConceptSwitch.AsynchronousRequestReply:
        if (props_AsynchronousRequestReply == null) {
          ConceptPresentationBuilder cpb = new ConceptPresentationBuilder();
          cpb.presentationByName();
          props_AsynchronousRequestReply = cpb.create();
        }
        return props_AsynchronousRequestReply;
      case LanguageConceptSwitch.Batch:
        if (props_Batch == null) {
          ConceptPresentationBuilder cpb = new ConceptPresentationBuilder();
          cpb.presentationByName();
          props_Batch = cpb.create();
        }
        return props_Batch;
      case LanguageConceptSwitch.Classify:
        if (props_Classify == null) {
          ConceptPresentationBuilder cpb = new ConceptPresentationBuilder();
          cpb.presentationByName();
          props_Classify = cpb.create();
        }
        return props_Classify;
      case LanguageConceptSwitch.Cleaning:
        if (props_Cleaning == null) {
          ConceptPresentationBuilder cpb = new ConceptPresentationBuilder();
          cpb.presentationByName();
          props_Cleaning = cpb.create();
        }
        return props_Cleaning;
      case LanguageConceptSwitch.ClientServerConnection:
        if (props_ClientServerConnection == null) {
          ConceptPresentationBuilder cpb = new ConceptPresentationBuilder();
          cpb.presentationByName();
          props_ClientServerConnection = cpb.create();
        }
        return props_ClientServerConnection;
      case LanguageConceptSwitch.Cloud:
        if (props_Cloud == null) {
          ConceptPresentationBuilder cpb = new ConceptPresentationBuilder();
          cpb.presentationByName();
          props_Cloud = cpb.create();
        }
        return props_Cloud;
      case LanguageConceptSwitch.Column:
        if (props_Column == null) {
          ConceptPresentationBuilder cpb = new ConceptPresentationBuilder();
          cpb.rawPresentation("Column");
          props_Column = cpb.create();
        }
        return props_Column;
      case LanguageConceptSwitch.Component:
        if (props_Component == null) {
          ConceptPresentationBuilder cpb = new ConceptPresentationBuilder();
          cpb.presentationByName();
          props_Component = cpb.create();
        }
        return props_Component;
      case LanguageConceptSwitch.ComponentBehavior:
        if (props_ComponentBehavior == null) {
          ConceptPresentationBuilder cpb = new ConceptPresentationBuilder();
          cpb.presentationByName();
          props_ComponentBehavior = cpb.create();
        }
        return props_ComponentBehavior;
      case LanguageConceptSwitch.Compress:
        if (props_Compress == null) {
          ConceptPresentationBuilder cpb = new ConceptPresentationBuilder();
          cpb.presentationByName();
          props_Compress = cpb.create();
        }
        return props_Compress;
      case LanguageConceptSwitch.ComputingUnit:
        if (props_ComputingUnit == null) {
          ConceptPresentationBuilder cpb = new ConceptPresentationBuilder();
          cpb.presentationByName();
          props_ComputingUnit = cpb.create();
        }
        return props_ComputingUnit;
      case LanguageConceptSwitch.Connection:
        if (props_Connection == null) {
          ConceptPresentationBuilder cpb = new ConceptPresentationBuilder();
          cpb.presentationByName();
          props_Connection = cpb.create();
        }
        return props_Connection;
      case LanguageConceptSwitch.ConnectionType:
        if (props_ConnectionType == null) {
          ConceptPresentationBuilder cpb = new ConceptPresentationBuilder();
          cpb.presentationByName();
          props_ConnectionType = cpb.create();
        }
        return props_ConnectionType;
      case LanguageConceptSwitch.ConsumingData:
        if (props_ConsumingData == null) {
          ConceptPresentationBuilder cpb = new ConceptPresentationBuilder();
          cpb.presentationByName();
          props_ConsumingData = cpb.create();
        }
        return props_ConsumingData;
      case LanguageConceptSwitch.DataArchitecture:
        if (props_DataArchitecture == null) {
          ConceptPresentationBuilder cpb = new ConceptPresentationBuilder();
          cpb.presentationByName();
          props_DataArchitecture = cpb.create();
        }
        return props_DataArchitecture;
      case LanguageConceptSwitch.DataGeneration:
        if (props_DataGeneration == null) {
          ConceptPresentationBuilder cpb = new ConceptPresentationBuilder();
          cpb.presentationByName();
          props_DataGeneration = cpb.create();
        }
        return props_DataGeneration;
      case LanguageConceptSwitch.DataIngestion:
        if (props_DataIngestion == null) {
          ConceptPresentationBuilder cpb = new ConceptPresentationBuilder();
          cpb.presentationByName();
          props_DataIngestion = cpb.create();
        }
        return props_DataIngestion;
      case LanguageConceptSwitch.DataLinkableElement:
        if (props_DataLinkableElement == null) {
          ConceptPresentationBuilder cpb = new ConceptPresentationBuilder();
          props_DataLinkableElement = cpb.create();
        }
        return props_DataLinkableElement;
      case LanguageConceptSwitch.DataLocation:
        if (props_DataLocation == null) {
          ConceptPresentationBuilder cpb = new ConceptPresentationBuilder();
          cpb.presentationByName();
          props_DataLocation = cpb.create();
        }
        return props_DataLocation;
      case LanguageConceptSwitch.DataPort:
        if (props_DataPort == null) {
          ConceptPresentationBuilder cpb = new ConceptPresentationBuilder();
          cpb.rawPresentation("DataPort");
          props_DataPort = cpb.create();
        }
        return props_DataPort;
      case LanguageConceptSwitch.DataProcessing:
        if (props_DataProcessing == null) {
          ConceptPresentationBuilder cpb = new ConceptPresentationBuilder();
          cpb.presentationByName();
          props_DataProcessing = cpb.create();
        }
        return props_DataProcessing;
      case LanguageConceptSwitch.Describe:
        if (props_Describe == null) {
          ConceptPresentationBuilder cpb = new ConceptPresentationBuilder();
          cpb.presentationByName();
          props_Describe = cpb.create();
        }
        return props_Describe;
      case LanguageConceptSwitch.Diagnoze:
        if (props_Diagnoze == null) {
          ConceptPresentationBuilder cpb = new ConceptPresentationBuilder();
          cpb.presentationByName();
          props_Diagnoze = cpb.create();
        }
        return props_Diagnoze;
      case LanguageConceptSwitch.Document:
        if (props_Document == null) {
          ConceptPresentationBuilder cpb = new ConceptPresentationBuilder();
          cpb.rawPresentation("Document");
          props_Document = cpb.create();
        }
        return props_Document;
      case LanguageConceptSwitch.Edge:
        if (props_Edge == null) {
          ConceptPresentationBuilder cpb = new ConceptPresentationBuilder();
          cpb.presentationByName();
          props_Edge = cpb.create();
        }
        return props_Edge;
      case LanguageConceptSwitch.EmbeddedFlashMemory:
        if (props_EmbeddedFlashMemory == null) {
          ConceptPresentationBuilder cpb = new ConceptPresentationBuilder();
          cpb.rawPresentation("EmbeddedFlashMemory");
          props_EmbeddedFlashMemory = cpb.create();
        }
        return props_EmbeddedFlashMemory;
      case LanguageConceptSwitch.Event:
        if (props_Event == null) {
          ConceptPresentationBuilder cpb = new ConceptPresentationBuilder();
          props_Event = cpb.create();
        }
        return props_Event;
      case LanguageConceptSwitch.FTP:
        if (props_FTP == null) {
          ConceptPresentationBuilder cpb = new ConceptPresentationBuilder();
          cpb.presentationByName();
          props_FTP = cpb.create();
        }
        return props_FTP;
      case LanguageConceptSwitch.FileSystems:
        if (props_FileSystems == null) {
          ConceptPresentationBuilder cpb = new ConceptPresentationBuilder();
          props_FileSystems = cpb.create();
        }
        return props_FileSystems;
      case LanguageConceptSwitch.Filter:
        if (props_Filter == null) {
          ConceptPresentationBuilder cpb = new ConceptPresentationBuilder();
          cpb.presentationByName();
          props_Filter = cpb.create();
        }
        return props_Filter;
      case LanguageConceptSwitch.Fog:
        if (props_Fog == null) {
          ConceptPresentationBuilder cpb = new ConceptPresentationBuilder();
          cpb.presentationByName();
          props_Fog = cpb.create();
        }
        return props_Fog;
      case LanguageConceptSwitch.Govern:
        if (props_Govern == null) {
          ConceptPresentationBuilder cpb = new ConceptPresentationBuilder();
          cpb.presentationByName();
          props_Govern = cpb.create();
        }
        return props_Govern;
      case LanguageConceptSwitch.Graph:
        if (props_Graph == null) {
          ConceptPresentationBuilder cpb = new ConceptPresentationBuilder();
          cpb.rawPresentation("Graph");
          props_Graph = cpb.create();
        }
        return props_Graph;
      case LanguageConceptSwitch.HTTP_HTTPS:
        if (props_HTTP_HTTPS == null) {
          ConceptPresentationBuilder cpb = new ConceptPresentationBuilder();
          cpb.presentationByName();
          props_HTTP_HTTPS = cpb.create();
        }
        return props_HTTP_HTTPS;
      case LanguageConceptSwitch.Historical:
        if (props_Historical == null) {
          ConceptPresentationBuilder cpb = new ConceptPresentationBuilder();
          cpb.rawPresentation("Historical");
          props_Historical = cpb.create();
        }
        return props_Historical;
      case LanguageConceptSwitch.IPFS:
        if (props_IPFS == null) {
          ConceptPresentationBuilder cpb = new ConceptPresentationBuilder();
          cpb.rawPresentation("IPFS");
          props_IPFS = cpb.create();
        }
        return props_IPFS;
      case LanguageConceptSwitch.Identify:
        if (props_Identify == null) {
          ConceptPresentationBuilder cpb = new ConceptPresentationBuilder();
          cpb.presentationByName();
          props_Identify = cpb.create();
        }
        return props_Identify;
      case LanguageConceptSwitch.InDataPort:
        if (props_InDataPort == null) {
          ConceptPresentationBuilder cpb = new ConceptPresentationBuilder();
          cpb.presentationByName();
          props_InDataPort = cpb.create();
        }
        return props_InDataPort;
      case LanguageConceptSwitch.Integrate:
        if (props_Integrate == null) {
          ConceptPresentationBuilder cpb = new ConceptPresentationBuilder();
          cpb.presentationByName();
          props_Integrate = cpb.create();
        }
        return props_Integrate;
      case LanguageConceptSwitch.KeyValue:
        if (props_KeyValue == null) {
          ConceptPresentationBuilder cpb = new ConceptPresentationBuilder();
          cpb.rawPresentation("KeyValue");
          props_KeyValue = cpb.create();
        }
        return props_KeyValue;
      case LanguageConceptSwitch.Link:
        if (props_Link == null) {
          ConceptPresentationBuilder cpb = new ConceptPresentationBuilder();
          cpb.presentationByName();
          props_Link = cpb.create();
        }
        return props_Link;
      case LanguageConceptSwitch.LoadBalancer:
        if (props_LoadBalancer == null) {
          ConceptPresentationBuilder cpb = new ConceptPresentationBuilder();
          cpb.presentationByName();
          props_LoadBalancer = cpb.create();
        }
        return props_LoadBalancer;
      case LanguageConceptSwitch.LocalStorage:
        if (props_LocalStorage == null) {
          ConceptPresentationBuilder cpb = new ConceptPresentationBuilder();
          props_LocalStorage = cpb.create();
        }
        return props_LocalStorage;
      case LanguageConceptSwitch.MQTT:
        if (props_MQTT == null) {
          ConceptPresentationBuilder cpb = new ConceptPresentationBuilder();
          cpb.presentationByName();
          props_MQTT = cpb.create();
        }
        return props_MQTT;
      case LanguageConceptSwitch.Math_Operation:
        if (props_Math_Operation == null) {
          ConceptPresentationBuilder cpb = new ConceptPresentationBuilder();
          cpb.presentationByName();
          props_Math_Operation = cpb.create();
        }
        return props_Math_Operation;
      case LanguageConceptSwitch.Merge:
        if (props_Merge == null) {
          ConceptPresentationBuilder cpb = new ConceptPresentationBuilder();
          cpb.presentationByName();
          props_Merge = cpb.create();
        }
        return props_Merge;
      case LanguageConceptSwitch.MessageQueueing:
        if (props_MessageQueueing == null) {
          ConceptPresentationBuilder cpb = new ConceptPresentationBuilder();
          cpb.presentationByName();
          props_MessageQueueing = cpb.create();
        }
        return props_MessageQueueing;
      case LanguageConceptSwitch.NVMe:
        if (props_NVMe == null) {
          ConceptPresentationBuilder cpb = new ConceptPresentationBuilder();
          cpb.rawPresentation("NVMe");
          props_NVMe = cpb.create();
        }
        return props_NVMe;
      case LanguageConceptSwitch.NetworkProtocols:
        if (props_NetworkProtocols == null) {
          ConceptPresentationBuilder cpb = new ConceptPresentationBuilder();
          cpb.presentationByName();
          props_NetworkProtocols = cpb.create();
        }
        return props_NetworkProtocols;
      case LanguageConceptSwitch.NewSQL:
        if (props_NewSQL == null) {
          ConceptPresentationBuilder cpb = new ConceptPresentationBuilder();
          props_NewSQL = cpb.create();
        }
        return props_NewSQL;
      case LanguageConceptSwitch.NoSQL:
        if (props_NoSQL == null) {
          ConceptPresentationBuilder cpb = new ConceptPresentationBuilder();
          props_NoSQL = cpb.create();
        }
        return props_NoSQL;
      case LanguageConceptSwitch.OutDataPort:
        if (props_OutDataPort == null) {
          ConceptPresentationBuilder cpb = new ConceptPresentationBuilder();
          cpb.presentationByName();
          props_OutDataPort = cpb.create();
        }
        return props_OutDataPort;
      case LanguageConceptSwitch.PointToPoint:
        if (props_PointToPoint == null) {
          ConceptPresentationBuilder cpb = new ConceptPresentationBuilder();
          cpb.presentationByName();
          props_PointToPoint = cpb.create();
        }
        return props_PointToPoint;
      case LanguageConceptSwitch.Predict:
        if (props_Predict == null) {
          ConceptPresentationBuilder cpb = new ConceptPresentationBuilder();
          cpb.presentationByName();
          props_Predict = cpb.create();
        }
        return props_Predict;
      case LanguageConceptSwitch.Prescript:
        if (props_Prescript == null) {
          ConceptPresentationBuilder cpb = new ConceptPresentationBuilder();
          cpb.presentationByName();
          props_Prescript = cpb.create();
        }
        return props_Prescript;
      case LanguageConceptSwitch.ProcessingType:
        if (props_ProcessingType == null) {
          ConceptPresentationBuilder cpb = new ConceptPresentationBuilder();
          cpb.presentationByName();
          props_ProcessingType = cpb.create();
        }
        return props_ProcessingType;
      case LanguageConceptSwitch.PublisherSubscriberConnection:
        if (props_PublisherSubscriberConnection == null) {
          ConceptPresentationBuilder cpb = new ConceptPresentationBuilder();
          cpb.presentationByName();
          props_PublisherSubscriberConnection = cpb.create();
        }
        return props_PublisherSubscriberConnection;
      case LanguageConceptSwitch.PushPull:
        if (props_PushPull == null) {
          ConceptPresentationBuilder cpb = new ConceptPresentationBuilder();
          cpb.presentationByName();
          props_PushPull = cpb.create();
        }
        return props_PushPull;
      case LanguageConceptSwitch.Qualitative:
        if (props_Qualitative == null) {
          ConceptPresentationBuilder cpb = new ConceptPresentationBuilder();
          cpb.presentationByName();
          props_Qualitative = cpb.create();
        }
        return props_Qualitative;
      case LanguageConceptSwitch.Quantitative:
        if (props_Quantitative == null) {
          ConceptPresentationBuilder cpb = new ConceptPresentationBuilder();
          cpb.presentationByName();
          props_Quantitative = cpb.create();
        }
        return props_Quantitative;
      case LanguageConceptSwitch.QueryReport:
        if (props_QueryReport == null) {
          ConceptPresentationBuilder cpb = new ConceptPresentationBuilder();
          cpb.presentationByName();
          props_QueryReport = cpb.create();
        }
        return props_QueryReport;
      case LanguageConceptSwitch.RealTime:
        if (props_RealTime == null) {
          ConceptPresentationBuilder cpb = new ConceptPresentationBuilder();
          cpb.presentationByName();
          props_RealTime = cpb.create();
        }
        return props_RealTime;
      case LanguageConceptSwitch.Real_Time:
        if (props_Real_Time == null) {
          ConceptPresentationBuilder cpb = new ConceptPresentationBuilder();
          cpb.rawPresentation("Real_Time");
          props_Real_Time = cpb.create();
        }
        return props_Real_Time;
      case LanguageConceptSwitch.ReceiveData:
        if (props_ReceiveData == null) {
          ConceptPresentationBuilder cpb = new ConceptPresentationBuilder();
          cpb.presentationByName();
          props_ReceiveData = cpb.create();
        }
        return props_ReceiveData;
      case LanguageConceptSwitch.ReduceNoise:
        if (props_ReduceNoise == null) {
          ConceptPresentationBuilder cpb = new ConceptPresentationBuilder();
          cpb.presentationByName();
          props_ReduceNoise = cpb.create();
        }
        return props_ReduceNoise;
      case LanguageConceptSwitch.RequestResponse:
        if (props_RequestResponse == null) {
          ConceptPresentationBuilder cpb = new ConceptPresentationBuilder();
          cpb.presentationByName();
          props_RequestResponse = cpb.create();
        }
        return props_RequestResponse;
      case LanguageConceptSwitch.Retrieve:
        if (props_Retrieve == null) {
          ConceptPresentationBuilder cpb = new ConceptPresentationBuilder();
          cpb.presentationByName();
          props_Retrieve = cpb.create();
        }
        return props_Retrieve;
      case LanguageConceptSwitch.SSDs:
        if (props_SSDs == null) {
          ConceptPresentationBuilder cpb = new ConceptPresentationBuilder();
          cpb.rawPresentation("SSDs");
          props_SSDs = cpb.create();
        }
        return props_SSDs;
      case LanguageConceptSwitch.Save:
        if (props_Save == null) {
          ConceptPresentationBuilder cpb = new ConceptPresentationBuilder();
          cpb.presentationByName();
          props_Save = cpb.create();
        }
        return props_Save;
      case LanguageConceptSwitch.SendData:
        if (props_SendData == null) {
          ConceptPresentationBuilder cpb = new ConceptPresentationBuilder();
          cpb.presentationByName();
          props_SendData = cpb.create();
        }
        return props_SendData;
      case LanguageConceptSwitch.Sort:
        if (props_Sort == null) {
          ConceptPresentationBuilder cpb = new ConceptPresentationBuilder();
          cpb.presentationByName();
          props_Sort = cpb.create();
        }
        return props_Sort;
      case LanguageConceptSwitch.Statistical:
        if (props_Statistical == null) {
          ConceptPresentationBuilder cpb = new ConceptPresentationBuilder();
          cpb.presentationByName();
          props_Statistical = cpb.create();
        }
        return props_Statistical;
      case LanguageConceptSwitch.StorageType:
        if (props_StorageType == null) {
          ConceptPresentationBuilder cpb = new ConceptPresentationBuilder();
          cpb.rawPresentation("StorageType");
          props_StorageType = cpb.create();
        }
        return props_StorageType;
      case LanguageConceptSwitch.StoringData:
        if (props_StoringData == null) {
          ConceptPresentationBuilder cpb = new ConceptPresentationBuilder();
          cpb.presentationByName();
          props_StoringData = cpb.create();
        }
        return props_StoringData;
      case LanguageConceptSwitch.Stream:
        if (props_Stream == null) {
          ConceptPresentationBuilder cpb = new ConceptPresentationBuilder();
          cpb.rawPresentation("Stream");
          props_Stream = cpb.create();
        }
        return props_Stream;
      case LanguageConceptSwitch.StreamProcessing:
        if (props_StreamProcessing == null) {
          ConceptPresentationBuilder cpb = new ConceptPresentationBuilder();
          cpb.presentationByName();
          props_StreamProcessing = cpb.create();
        }
        return props_StreamProcessing;
      case LanguageConceptSwitch.TCP_IP:
        if (props_TCP_IP == null) {
          ConceptPresentationBuilder cpb = new ConceptPresentationBuilder();
          cpb.presentationByName();
          props_TCP_IP = cpb.create();
        }
        return props_TCP_IP;
      case LanguageConceptSwitch.Technique:
        if (props_Technique == null) {
          ConceptPresentationBuilder cpb = new ConceptPresentationBuilder();
          cpb.presentationByName();
          props_Technique = cpb.create();
        }
        return props_Technique;
      case LanguageConceptSwitch.TimeStamp:
        if (props_TimeStamp == null) {
          ConceptPresentationBuilder cpb = new ConceptPresentationBuilder();
          cpb.rawPresentation("TimeStamp");
          props_TimeStamp = cpb.create();
        }
        return props_TimeStamp;
      case LanguageConceptSwitch.Transform:
        if (props_Transform == null) {
          ConceptPresentationBuilder cpb = new ConceptPresentationBuilder();
          cpb.presentationByName();
          props_Transform = cpb.create();
        }
        return props_Transform;
      case LanguageConceptSwitch.Transforme:
        if (props_Transforme == null) {
          ConceptPresentationBuilder cpb = new ConceptPresentationBuilder();
          cpb.presentationByName();
          props_Transforme = cpb.create();
        }
        return props_Transforme;
      case LanguageConceptSwitch.Type:
        if (props_Type == null) {
          ConceptPresentationBuilder cpb = new ConceptPresentationBuilder();
          cpb.presentationByName();
          props_Type = cpb.create();
        }
        return props_Type;
      case LanguageConceptSwitch.Validate:
        if (props_Validate == null) {
          ConceptPresentationBuilder cpb = new ConceptPresentationBuilder();
          cpb.presentationByName();
          props_Validate = cpb.create();
        }
        return props_Validate;
      case LanguageConceptSwitch.Visualize:
        if (props_Visualize == null) {
          ConceptPresentationBuilder cpb = new ConceptPresentationBuilder();
          cpb.presentationByName();
          props_Visualize = cpb.create();
        }
        return props_Visualize;
      case LanguageConceptSwitch.WebSocket:
        if (props_WebSocket == null) {
          ConceptPresentationBuilder cpb = new ConceptPresentationBuilder();
          cpb.presentationByName();
          props_WebSocket = cpb.create();
        }
        return props_WebSocket;
    }
    return null;
  }
}
